//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commidity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commidity()
        {
            this.NoskheCommidity = new HashSet<NoskheCommidity>();
        }
    
        public int CommidityID { get; set; }
        public string CommidityName { get; set; }
        public string CommidityDetile { get; set; }
        public int CommidityTypeID { get; set; }
        public long CommidityPrice { get; set; }
    
        public virtual CommidityType CommidityType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoskheCommidity> NoskheCommidity { get; set; }
    }
}
