//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInfo
    {
        public int CustomerInfoID { get; set; }
        public string CustomerInfoPicName { get; set; }
        public byte[] CustomerInfoData { get; set; }
        public int CustomerID { get; set; }
        public string CustomerInfoVazn { get; set; }
        public string CustomerInfoGhad { get; set; }
        public System.DateTime CustomerInfoRegDate { get; set; }
        public string FileName { get; set; }
        public string ContentType { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
