//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorNewCommidity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoctorNewCommidity()
        {
            this.DoctorComInfo = new HashSet<DoctorComInfo>();
        }
    
        public int DoctorNewCommidityID { get; set; }
        public string DoctorNewCommidityName { get; set; }
        public string DoctorNewCommidityProperty { get; set; }
        public string DoctorNewCommidityIndication { get; set; }
        public string DoctorNewCommidityUnIndication { get; set; }
        public bool SellToAnother { get; set; }
        public bool SendToAdvertising { get; set; }
        public string HowToUse { get; set; }
        public int DoctorID { get; set; }
        public System.DateTime DoctorNewCommidityDate { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorComInfo> DoctorComInfo { get; set; }
    }
}
