//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.Customer = new HashSet<Customer>();
            this.DoctorNewCommidity = new HashSet<DoctorNewCommidity>();
        }
    
        public int DoctorID { get; set; }
        public string DoctorFullName { get; set; }
        public long DoctorTel { get; set; }
        public long DoctorMobile { get; set; }
        public string DoctorEmail { get; set; }
        public string DoctorDescription { get; set; }
        public long DoctorNumber { get; set; }
        public string DoctorAddress { get; set; }
        public int ShahrestanID { get; set; }
        public string DoctorPassWord { get; set; }
    
        public virtual Shahrestan Shahrestan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorNewCommidity> DoctorNewCommidity { get; set; }
    }
}
