//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorComInfo
    {
        public int DoctorComInfoID { get; set; }
        public string DoctorComInfoName { get; set; }
        public string DoctorComInfoSize { get; set; }
        public int DoctorNewCommidityID { get; set; }
    
        public virtual DoctorNewCommidity DoctorNewCommidity { get; set; }
    }
}
