//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewDoctorEntities : DbContext
    {
        public NewDoctorEntities()
            : base("name=NewDoctorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Doctor> Doctor { get; set; }
        public virtual DbSet<Ostan> Ostan { get; set; }
        public virtual DbSet<Shahrestan> Shahrestan { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Commidity> Commidity { get; set; }
        public virtual DbSet<CommidityType> CommidityType { get; set; }
        public virtual DbSet<Noskhe> Noskhe { get; set; }
        public virtual DbSet<NoskheCommidity> NoskheCommidity { get; set; }
        public virtual DbSet<Sabeghe> Sabeghe { get; set; }
        public virtual DbSet<DoctorComInfo> DoctorComInfo { get; set; }
        public virtual DbSet<DoctorNewCommidity> DoctorNewCommidity { get; set; }
        public virtual DbSet<SellNoskhe> SellNoskhe { get; set; }
        public virtual DbSet<CustomerInfo> CustomerInfo { get; set; }
        public virtual DbSet<Post> Post { get; set; }
    }
}
