//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoskheCommidity
    {
        public int NoskheID { get; set; }
        public int CommidityID { get; set; }
        public int Number { get; set; }
        public long PriceInDay { get; set; }
    
        public virtual Commidity Commidity { get; set; }
        public virtual Noskhe Noskhe { get; set; }
    }
}
