//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int PostID { get; set; }
        public string PostTitle { get; set; }
        public string PostDetile { get; set; }
        public string PostBody { get; set; }
        public string PostDate { get; set; }
        public byte[] PostImageData { get; set; }
        public string PostFileName { get; set; }
        public string PostContentType { get; set; }
    }
}
